### PR TITLE
Add more flexible way to control message encoding

### PR DESCRIPTION
**Pull request by gordeevnm**

### CODE REVIEW

**Comment by ivantopo** [comment]
This would be a really great addition, specially for folks wanting to leverage the logstash encoder to produce json messages! Hope this gets in soon 🙏

**Comment by nehaev** [comment]
Hi @gordeevnm and @ivantopo, thanks for your contribution! Loki4j already has Json and Protobuf encoders for Loki message format. What you suggest is encoder inside the encoder. I think it's out of scope for a simple and lightweight log appender that Loki4j is trying to be. Sorry.

**Comment by gordeevnm** [comment]
As far as I understand the encoders that loki4j has are transport layer encoders, but the encoder in the PR is a higher level(application level) thing. For example, now loki4j doesn't provide a way to send all MDC content in message, also you can only send messages in logfmt format, which is not always useful

**Comment by nehaev** [comment]
@gordeevnm, thanks for your feedback! Yes, I see that this encoder is a higher level thing. I'm just saying that adding the ability to use a custom encoder will complicate things a bit and make loki4j both harder to use and to maintain.

However, I'm struggling to understand what use case do you have in mind. Why do you need to send all MDC content in message? Why json format is better than the plain text? Looks like you want to search by the content of the message, which is exactly the thing Loki isn't that good in.

**Comment by gordeevnm** [comment]
@nehaev I usually put in MDC an business entity id so I can then find all logs about this entity. It's super useful when you see an alert with an error and you can filter logs by the entity id and see all messages about the entity processing, and you don't need to put entity id everywhere manually - just put the MDC value once. 
Second usecase - we use tracing and opentelemetry puts trace-id to MDC, so then we can correlate trace with logs in grafana
About json vs. plain/logfmt - I just use "| json", "| label_format" and "| line_format" in logql, so I can manipulate string as I want without additional parsing or line processing. And json the only one format I know that doesn't make your feel pain about multiline messages(stacktraces).
I understand that loki isn't good in searching, but we're ok with O(n) complexity filtering logs in a narrow range

// Also I use json appender that provides ability to filter stack frames(useless proxies, *.reflect.*.invoke, etc) and compress stack frame's length(j.u.c.* instead of java.util.concurrent.*, for example), so I have concise stacktraces in logs. I'd say it's specific case, but I want to save such functionalities.

**Pull request closed without merging**
